# Dockerfile

FROM php:8.2-apache

RUN apt-get update && \
    apt-get install -y libsqlite3-dev \
    && docker-php-ext-install pdo_sqlite


RUN a2enmod rewrite

RUN rm -rf /var/www/html

COPY . /var/www/html


RUN chown -R www-data:www-data /var/www/html

EXPOSE 80